trigger: 
  - main
  - feature/*

pool: dev-pool

variables:
  WORK_DIR: '$(System.DefaultWorkingDirectory)/Env-Infra/dev/'
  SPN: 'DaasWealth'

stages:
- stage: precheck
  displayName: PRECHECK | Terraform Quality & Validation
  pool: dev-pool
  jobs:
    - job: Plan
      displayName: Terraform Pre-Validation
      steps:

        - task: Bash@3
          displayName: System Prep | Install OS Dependencies
          inputs:
            targetType: 'inline'
            script: |
              sudo apt-get update
              sudo apt-get install unzip -y
              unzip -v

        - task: TerraformInstaller@1
          displayName: Terraform | Install CLI
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform | Init (Remote Backend)
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(WORK_DIR)'
            backendServiceArm: '$(SPN)'
            backendAzureRmStorageAccountName: '$(BACKEND-STORAGE)'
            backendAzureRmContainerName: 'data'
            backendAzureRmKey: 'dev.tfstate'

        - task: TerraformTask@5
          displayName: Terraform | Format Check
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(WORK_DIR)'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: '$(SPN)'

        - task: TerraformTask@5
          displayName: Terraform | Validate Configuration
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(WORK_DIR)'
            outputTo: 'console'
            customCommand: 'validate'
            environmentServiceNameAzureRM: '$(SPN)'


- stage: SecureScan
  displayName: SECURITY | Static Analysis & Linting
  pool: dev-pool
  jobs:

  - job: SecurityAnalaysis
    displayName: Security Scan | tfsec
    steps:
      - task: Bash@3
        displayName: tfsec | Install & Scan IaC
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
            tfsec .

  - job: CodeScanningLinting
    displayName: Code Quality | TFLint
    steps:

      - task: Bash@3
        displayName: TFLint | Install CLI
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - task: Bash@3
        displayName: TFLint | Initialize Rules
        inputs:
          targetType: 'inline'
          script: |
            tflint --init

- stage: TerraformTest
  displayName: Terratest | Infra Validation
  jobs:
  - job: Terratesting
    displayName: Run Terratest
    pool: dev-pool

    steps:
    - checkout: self

    - task: GoTool@0
      displayName: Install Go
      inputs:
        version: '1.23'

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: Azure Login
      inputs:
        azureSubscription: '$(SPN)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    - script: |
        go mod tidy
        go test ./test -v
      displayName: Run Terratest
      workingDirectory: '$(System.DefaultWorkingDirectory)/Env-Infra/terratest/test'

          



##Manual Validation --Step

- stage: approval
  displayName: APPROVAL | Manual Validation Gate
  jobs:
  - job: ManualApproval
    displayName: Change Approval
    pool: server
    steps:
    - task: ManualValidation@1
      displayName: Await Manual Approval
      inputs:
        notifyUsers: 'falana@gmail.com'

- stage: Apply
  displayName: DEPLOY | Terraform Apply
  pool: dev-pool
  jobs:
    - job: Deploy_Infra
      displayName: Infrastructure Deployment
      steps:

        - task: TerraformInstaller@1
          displayName: Terraform | Install CLI
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform | Init (Apply Stage)
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(WORK_DIR)'
            backendServiceArm: '$(SPN)'
            backendAzureRmStorageAccountName: 'az3tirestorage01'
            backendAzureRmContainerName: 'data'
            backendAzureRmKey: 'dev.tfstate'

        - task: TerraformTask@5
          displayName: Terraform | Apply Infrastructure
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(WORK_DIR)'
            environmentServiceNameAzureRM: '$(SPN)'

