trigger: none

parameters:
- name: Env
  type: string
  values:
    - dev
    - prod

variables:
  WORK_DIR: '$(System.DefaultWorkingDirectory)/Env-Infra/${{ parameters.Env }}/'
  SPN: 'DaasWealth'

stages:
  - stage: precheck
    displayName: PRECHECK | Terraform Quality & Validation
    pool: ${{ parameters.Env }}-pool
    jobs:
      - job: Plan
        displayName: Terraform Pre-Validation
        steps:
          - task: Bash@3
            displayName: System Prep | Install OS Packages
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update
                sudo apt-get install unzip -y
                unzip -v

          - task: TerraformInstaller@1
            displayName: Terraform | Install CLI
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform | Init Backend
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(WORK_DIR)'
              backendServiceArm: '$(SPN)'
              backendAzureRmStorageAccountName: 'az3tirestorage01'
              backendAzureRmContainerName: 'data'
              backendAzureRmKey: 'dev.tfstate'

          - task: TerraformTask@5
            displayName: Terraform | Format Check
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(WORK_DIR)'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: '$(SPN)'

          - task: TerraformTask@5
            displayName: Terraform | Validate Configuration
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(WORK_DIR)'
              outputTo: 'console'
              customCommand: 'validate'
              environmentServiceNameAzureRM: '$(SPN)'            


  - stage: SecureScan
    displayName: SECURITY | Static Analysis & Linting
    pool: ${{ parameters.Env }}-pool
    jobs:
    - job: SecnLinting
      displayName: Security Scan | tfsec
      steps: 
        - task: Bash@3
          displayName: tfsec | Install & Scan IaC
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash 
              tfsec .      

    - job: CodeLinting
      displayName: Code Quality | TFLint
      steps:               
        - task: Bash@3
          displayName: TFLint | Install, Init & Lint
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint --init
              tflint

    - job: TerraPlan
      displayName: Terraform Plan Generation
      steps: 
        - task: TerraformTask@5
          displayName: Terraform | Init for Plan
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(WORK_DIR)'
            backendServiceArm: '$(SPN)'
            backendAzureRmStorageAccountName: 'az3tirestorage01'
            backendAzureRmContainerName: 'data'
            backendAzureRmKey: 'dev.tfstate'            
            
  - stage: TerraformTest
    displayName: Terratest | Infra Validation
    jobs:
    - job: Terratesting
      displayName: Run Terratest
      pool: ${{ parameters.Env }}-pool

      steps:
      - checkout: self

      - task: GoTool@0
        displayName: Install Go
        inputs:
          version: '1.23'

      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'

      - task: AzureCLI@2
        displayName: Azure Login
        inputs:
          azureSubscription: '$(SPN)'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az account show

      - script: |
          go mod tidy
          go test 
        displayName: Run Terratest
        workingDirectory: '$(System.DefaultWorkingDirectory)/Env-Infra/terratest/test'


  - stage: approval
    displayName: APPROVAL | Manual Validation Gate
    jobs:
    - job: ManualApproval
      displayName: Production Change Approval
      pool: server
      steps:
      - task: ManualValidation@1
        displayName: Await Manual Approval
        inputs:
          notifyUsers: 'falana@gmail.com'


  - stage: Apply
    displayName: DEPLOY | Terraform Apply
    pool: ${{ parameters.Env }}-pool
    jobs:
    - job: Deploy_Infra
      displayName: Infrastructure Deployment
      steps:

      - task: TerraformInstaller@1
        displayName: Terraform | Install CLI
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform | Init (Apply)
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(WORK_DIR)'
          backendServiceArm: '$(SPN)'
          backendAzureRmStorageAccountName: 'az3tirestorage01'
          backendAzureRmContainerName: 'data'
          backendAzureRmKey: 'dev.tfstate'

      - task: TerraformTask@5
        displayName: Terraform | Apply Infrastructure
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(WORK_DIR)'
          environmentServiceNameAzureRM: '$(SPN)'

